/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    Btn: typeof import('./components/Btn.vue')['default']
    Checkbox: typeof import('./components/Form/Field/Checkbox.vue')['default']
    DropFile: typeof import('./components/Form/DropFile.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Input: typeof import('./components/Form/Field/Input.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    Mnemonic: typeof import('./components/Mnemonic.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    NftCard: typeof import('./components/NftCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/Spinner.vue')['default']
    SvgInclude: typeof import('./components/SvgInclude.vue')['default']
    Textarea: typeof import('./components/Form/Field/Textarea.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
