/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimatedImage: typeof import('./components/Animation/AnimatedImage.vue')['default']
    Btn: typeof import('./components/general/Btn.vue')['default']
    DropFile: typeof import('./components/Form/DropFile.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    Icons: typeof import('./components/Animation/Icons.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Loader: typeof import('./components/Animation/Loader.vue')['default']
    Modal: typeof import('./components/general/Modal.vue')['default']
    NftCard: typeof import('./components/NftCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/Animation/Spinner.vue')['default']
    SvgInclude: typeof import('./components/general/SvgInclude.vue')['default']
  }
}
