/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimatedImage: typeof import('./components/general/Animation/AnimatedImage.vue')['default']
    Btn: typeof import('./components/general/Btn.vue')['default']
    ConnectWallet: typeof import('./components/parts/ConnectWallet.vue')['default']
    DropFile: typeof import('./components/general/Form/DropFile.vue')['default']
    Footer: typeof import('./components/parts/Footer.vue')['default']
    Header: typeof import('./components/parts/Header.vue')['default']
    IconCommunity: typeof import('./components/general/Icon/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/general/Icon/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/general/Icon/IconEcosystem.vue')['default']
    Icons: typeof import('./components/general/Animation/Icons.vue')['default']
    IconSupport: typeof import('./components/general/Icon/IconSupport.vue')['default']
    IconTooling: typeof import('./components/general/Icon/IconTooling.vue')['default']
    Loader: typeof import('./components/general/Animation/Loader.vue')['default']
    Modal: typeof import('./components/general/Modal.vue')['default']
    NftCard: typeof import('./components/parts/NftCard.vue')['default']
    Nfts: typeof import('./components/parts/Nfts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/general/Animation/Spinner.vue')['default']
    SvgInclude: typeof import('./components/general/SvgInclude.vue')['default']
    Wallet: typeof import('./components/general/Form/Wallet.vue')['default']
  }
}
